package fox.mods.api.economy.configuration;

import net.minecraftforge.common.ForgeConfigSpec;

public class EconomyPricesFileConfiguration {

    public static final ForgeConfigSpec.Builder BUILDER = new ForgeConfigSpec.Builder();
    public static final ForgeConfigSpec SPEC;

    public static final ForgeConfigSpec.ConfigValue<Double> STONE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> GRASS_BLOCK_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> DIRT_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> COBBLESTONE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> OAK_PLANKS_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> SPRUCE_PLANKS_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> BIRCH_PLANKS_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> SAND_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> GRAVEL_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> GOLD_ORE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> IRON_ORE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> COAL_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> DIAMOND_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> EMERALD_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> REDSTONE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> LAPIS_LAZULI_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> OBSIDIAN_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> GOLD_INGOT_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> IRON_INGOT_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> COAL_BLOCK_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> DIAMOND_BLOCK_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> EMERALD_BLOCK_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> REDSTONE_BLOCK_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> LAPIS_BLOCK_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> NETHERITE_INGOT_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> QUARTZ_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> SLIME_BALL_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> ENDER_PEARL_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> STRING_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> FEATHER_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> LEATHER_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> BONE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> SUGAR_CANE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> PAPER_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> BOOK_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> GUNPOWDER_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> BLAZE_ROD_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> GHAST_TEAR_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> MAGMA_CREAM_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> PHANTOM_MEMBRANE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> ELYTRA_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> SHULKER_SHELL_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> PRISMARINE_SHARD_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> PRISMARINE_CRYSTALS_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> SEA_LANTERN_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> HEART_OF_THE_SEA_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> TURTLE_HELMET_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> TRIDENT_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> HONEY_BOTTLE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> COPPER_ORE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> COPPER_INGOT_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> AMETHYST_SHARD_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> ANCIENT_DEBRIS_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> NETHERITE_SCRAP_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> RAW_GOLD_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> RAW_IRON_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> RAW_COPPER_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> GOLD_BLOCK_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> IRON_BLOCK_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> COPPER_BLOCK_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> QUARTZ_BLOCK_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> LAPIS_ORE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> REDSTONE_ORE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> DIAMOND_ORE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> EMERALD_ORE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> NETHER_GOLD_ORE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> NETHER_QUARTZ_ORE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> DEEPSLATE_DIAMOND_ORE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> DEEPSLATE_EMERALD_ORE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> DEEPSLATE_GOLD_ORE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> DEEPSLATE_IRON_ORE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> DEEPSLATE_LAPIS_ORE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> DEEPSLATE_REDSTONE_ORE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> DEEPSLATE_COPPER_ORE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> GLOWSTONE_DUST_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> CRYING_OBSIDIAN_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> SPONGE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> GILDED_BLACKSTONE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> BEE_NEST_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> HONEYCOMB_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> TOTEM_OF_UNDYING_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> BEACON_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> DRAGON_EGG_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> DRAGON_HEAD_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> WITHER_SKELETON_SKULL_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> NETHERITE_BLOCK_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> ANCIENT_CITY_REINFORCED_DEEPSLATE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> ENCHANTED_GOLDEN_APPLE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> STONE_BRICKS_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> MOSSY_STONE_BRICKS_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> CRACKED_STONE_BRICKS_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> CHISELED_STONE_BRICKS_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> BRICKS_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> CLAY_BLOCK_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> TERRACOTTA_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> WHITE_TERRACOTTA_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> ORANGE_TERRACOTTA_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> MAGENTA_TERRACOTTA_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> LIGHT_BLUE_TERRACOTTA_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> YELLOW_TERRACOTTA_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> LIME_TERRACOTTA_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> PINK_TERRACOTTA_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> GRAY_TERRACOTTA_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> LIGHT_GRAY_TERRACOTTA_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> CYAN_TERRACOTTA_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> PURPLE_TERRACOTTA_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> BLUE_TERRACOTTA_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> BROWN_TERRACOTTA_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> GREEN_TERRACOTTA_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> RED_TERRACOTTA_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> BLACK_TERRACOTTA_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> SANDSTONE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> SMOOTH_SANDSTONE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> CUT_SANDSTONE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> CHISELED_SANDSTONE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> OAK_LOG_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> OAK_PLANK_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> WHITE_WOOL_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> CONCRETE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> GLASS_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> STAINED_GLASS_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> ANDESITE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> POLISHED_ANDESITE_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> BASALT_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> POLISHED_BASALT_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> PURPUR_BLOCK_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> BOOKSHELF_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> HAY_BLOCK_COST;
    public static final ForgeConfigSpec.ConfigValue<Double> SLIME_BLOCK_COST;

    static {
        BUILDER.push("Economy Prices Settings");

        STONE_COST = BUILDER.comment("Price for Stone.").define("Stone", 0.5);
        GRASS_BLOCK_COST = BUILDER.comment("Price for Grass Block.").define("Grass Block", 0.2);
        DIRT_COST = BUILDER.comment("Price for Dirt.").define("Dirt", 0.1);
        COBBLESTONE_COST = BUILDER.comment("Price for Cobblestone.").define("Cobblestone", 0.3);
        OAK_PLANKS_COST = BUILDER.comment("Price for Oak Planks.").define("Oak Planks", 0.5);
        SPRUCE_PLANKS_COST = BUILDER.comment("Price for Spruce Planks.").define("Spruce Planks", 0.5);
        BIRCH_PLANKS_COST = BUILDER.comment("Price for Birch Planks.").define("Birch Planks", 0.5);
        SAND_COST = BUILDER.comment("Price for Sand.").define("Sand", 0.2);
        GRAVEL_COST = BUILDER.comment("Price for Gravel.").define("Gravel", 0.15);
        GOLD_ORE_COST = BUILDER.comment("Price for Gold Ore.").define("Gold Ore", 5.0);
        IRON_ORE_COST = BUILDER.comment("Price for Iron Ore.").define("Iron Ore", 3.0);
        COAL_COST = BUILDER.comment("Price for Coal.").define("Coal", 0.8);
        DIAMOND_COST = BUILDER.comment("Price for Diamond.").define("Diamond", 50.0);
        EMERALD_COST = BUILDER.comment("Price for Emerald.").define("Emerald", 40.0);
        REDSTONE_COST = BUILDER.comment("Price for Redstone.").define("Redstone", 1.5);
        LAPIS_LAZULI_COST = BUILDER.comment("Price for Lapis Lazuli.").define("Lapis Lazuli", 1.2);
        OBSIDIAN_COST = BUILDER.comment("Price for Obsidian.").define("Obsidian", 10.0);
        GOLD_INGOT_COST = BUILDER.comment("Price for Gold Ingot.").define("Gold Ingot", 6.0);
        IRON_INGOT_COST = BUILDER.comment("Price for Iron Ingot.").define("Iron Ingot", 4.0);
        COAL_BLOCK_COST = BUILDER.comment("Price for Coal Block.").define("Coal Block", 7.2);
        DIAMOND_BLOCK_COST = BUILDER.comment("Price for Diamond Block.").define("Diamond Block", 450.0);
        EMERALD_BLOCK_COST = BUILDER.comment("Price for Emerald Block.").define("Emerald Block", 360.0);
        REDSTONE_BLOCK_COST = BUILDER.comment("Price for Redstone Block.").define("Redstone Block", 13.5);
        LAPIS_BLOCK_COST = BUILDER.comment("Price for Lapis Block.").define("Lapis Block", 10.8);
        NETHERITE_INGOT_COST = BUILDER.comment("Price for Netherite Ingot.").define("Netherite Ingot", 100.0);
        QUARTZ_COST = BUILDER.comment("Price for Quartz.").define("Quartz", 1.0);
        SLIME_BALL_COST = BUILDER.comment("Price for Slime Ball.").define("Slime Ball", 5.0);
        ENDER_PEARL_COST = BUILDER.comment("Price for Ender Pearl.").define("Ender Pearl", 10.0);
        STRING_COST = BUILDER.comment("Price for String.").define("String", 0.5);
        FEATHER_COST = BUILDER.comment("Price for Feather.").define("Feather", 0.3);
        LEATHER_COST = BUILDER.comment("Price for Leather.").define("Leather", 2.0);
        BONE_COST = BUILDER.comment("Price for Bone.").define("Bone", 1.5);
        SUGAR_CANE_COST = BUILDER.comment("Price for Sugar Cane.").define("Sugar Cane", 0.2);
        PAPER_COST = BUILDER.comment("Price for Paper.").define("Paper", 0.5);
        BOOK_COST = BUILDER.comment("Price for Book.").define("Book", 3.0);
        GUNPOWDER_COST = BUILDER.comment("Price for Gunpowder.").define("Gunpowder", 2.5);
        BLAZE_ROD_COST = BUILDER.comment("Price for Blaze Rod.").define("Blaze Rod", 15.0);
        GHAST_TEAR_COST = BUILDER.comment("Price for Ghast Tear.").define("Ghast Tear", 20.0);
        MAGMA_CREAM_COST = BUILDER.comment("Price for Magma Cream.").define("Magma Cream", 7.0);
        PHANTOM_MEMBRANE_COST = BUILDER.comment("Price for Phantom Membrane.").define("Phantom Membrane", 10.0);
        ELYTRA_COST = BUILDER.comment("Price for Elytra.").define("Elytra", 200.0);
        SHULKER_SHELL_COST = BUILDER.comment("Price for Shulker Shell.").define("Shulker Shell", 25.0);
        PRISMARINE_SHARD_COST = BUILDER.comment("Price for Prismarine Shard.").define("Prismarine Shard", 4.0);
        PRISMARINE_CRYSTALS_COST = BUILDER.comment("Price for Prismarine Crystals.").define("Prismarine Crystals", 5.0);
        SEA_LANTERN_COST = BUILDER.comment("Price for Sea Lantern.").define("Sea Lantern", 12.0);
        HEART_OF_THE_SEA_COST = BUILDER.comment("Price for Heart of the Sea.").define("Heart of the Sea", 50.0);
        TURTLE_HELMET_COST = BUILDER.comment("Price for Turtle Helmet.").define("Turtle Helmet", 15.0);
        TRIDENT_COST = BUILDER.comment("Price for Trident.").define("Trident", 100.0);
        HONEY_BOTTLE_COST = BUILDER.comment("Price for Honey Bottle.").define("Honey Bottle", 3.0);
        COPPER_ORE_COST = BUILDER.comment("Price for Copper Ore.").define("Copper Ore", 1.5);
        COPPER_INGOT_COST = BUILDER.comment("Price for Copper Ingot.").define("Copper Ingot", 2.0);
        AMETHYST_SHARD_COST = BUILDER.comment("Price for Amethyst Shard.").define("Amethyst Shard", 5.0);
        ANCIENT_DEBRIS_COST = BUILDER.comment("Price for Ancient Debris.").define("Ancient Debris", 75.0);
        NETHERITE_SCRAP_COST = BUILDER.comment("Price for Netherite Scrap.").define("Netherite Scrap", 25.0);
        RAW_GOLD_COST = BUILDER.comment("Price for Raw Gold.").define("Raw Gold", 4.5);
        RAW_IRON_COST = BUILDER.comment("Price for Raw Iron.").define("Raw Iron", 3.5);
        RAW_COPPER_COST = BUILDER.comment("Price for Raw Copper.").define("Raw Copper", 1.8);
        GOLD_BLOCK_COST = BUILDER.comment("Price for Gold Block.").define("Gold Block", 54.0);
        IRON_BLOCK_COST = BUILDER.comment("Price for Iron Block.").define("Iron Block", 36.0);
        COPPER_BLOCK_COST = BUILDER.comment("Price for Copper Block.").define("Copper Block", 18.0);
        QUARTZ_BLOCK_COST = BUILDER.comment("Price for Quartz Block.").define("Quartz Block", 4.0);
        LAPIS_ORE_COST = BUILDER.comment("Price for Lapis Ore.").define("Lapis Ore", 6.0);
        REDSTONE_ORE_COST = BUILDER.comment("Price for Redstone Ore.").define("Redstone Ore", 8.0);
        DIAMOND_ORE_COST = BUILDER.comment("Price for Diamond Ore.").define("Diamond Ore", 55.0);
        EMERALD_ORE_COST = BUILDER.comment("Price for Emerald Ore.").define("Emerald Ore", 45.0);
        NETHER_GOLD_ORE_COST = BUILDER.comment("Price for Nether Gold Ore.").define("Nether Gold Ore", 5.5);
        NETHER_QUARTZ_ORE_COST = BUILDER.comment("Price for Nether Quartz Ore.").define("Nether Quartz Ore", 3.0);
        DEEPSLATE_DIAMOND_ORE_COST = BUILDER.comment("Price for Deepslate Diamond Ore.").define("Deepslate Diamond Ore", 60.0);
        DEEPSLATE_EMERALD_ORE_COST = BUILDER.comment("Price for Deepslate Emerald Ore.").define("Deepslate Emerald Ore", 50.0);
        DEEPSLATE_GOLD_ORE_COST = BUILDER.comment("Price for Deepslate Gold Ore.").define("Deepslate Gold Ore", 6.0);
        DEEPSLATE_IRON_ORE_COST = BUILDER.comment("Price for Deepslate Iron Ore.").define("Deepslate Iron Ore", 4.0);
        DEEPSLATE_LAPIS_ORE_COST = BUILDER.comment("Price for Deepslate Lapis Ore.").define("Deepslate Lapis Ore", 6.5);
        DEEPSLATE_REDSTONE_ORE_COST = BUILDER.comment("Price for Deepslate Redstone Ore.").define("Deepslate Redstone Ore", 9.0);
        DEEPSLATE_COPPER_ORE_COST = BUILDER.comment("Price for Deepslate Copper Ore.").define("Deepslate Copper Ore", 2.0);
        GLOWSTONE_DUST_COST = BUILDER.comment("Price for Glowstone Dust.").define("Glowstone Dust", 1.5);
        CRYING_OBSIDIAN_COST = BUILDER.comment("Price for Crying Obsidian.").define("Crying Obsidian", 10.0);
        SPONGE_COST = BUILDER.comment("Price for Sponge.").define("Sponge", 15.0);
        GILDED_BLACKSTONE_COST = BUILDER.comment("Price for Gilded Blackstone.").define("Gilded Blackstone", 7.5);
        BEE_NEST_COST = BUILDER.comment("Price for Bee Nest.").define("Bee Nest", 12.0);
        HONEYCOMB_COST = BUILDER.comment("Price for Honeycomb.").define("Honeycomb", 2.0);
        TOTEM_OF_UNDYING_COST = BUILDER.comment("Price for Totem of Undying.").define("Totem of Undying", 50.0);
        BEACON_COST = BUILDER.comment("Price for Beacon.").define("Beacon", 150.0);
        DRAGON_EGG_COST = BUILDER.comment("Price for Dragon Egg.").define("Dragon Egg", 500.0);
        DRAGON_HEAD_COST = BUILDER.comment("Price for Dragon Head.").define("Dragon Head", 75.0);
        WITHER_SKELETON_SKULL_COST = BUILDER.comment("Price for Wither Skeleton Skull.").define("Wither Skeleton Skull", 40.0);
        NETHERITE_BLOCK_COST = BUILDER.comment("Price for Netherite Block.").define("Netherite Block", 900.0);
        ANCIENT_CITY_REINFORCED_DEEPSLATE_COST = BUILDER.comment("Price for Ancient City Reinforced Deepslate.").define("Ancient City Reinforced Deepslate", 250.0);
        ENCHANTED_GOLDEN_APPLE_COST = BUILDER.comment("Price for Enchanted Golden Apple.").define("Enchanted Golden Apple", 100.0);
        STONE_BRICKS_COST = BUILDER.comment("Price for Stone Bricks.").define("Stone Bricks", 2.5);
        MOSSY_STONE_BRICKS_COST = BUILDER.comment("Price for Mossy Stone Bricks.").define("Mossy Stone Bricks", 2.7);
        CRACKED_STONE_BRICKS_COST = BUILDER.comment("Price for Cracked Stone Bricks.").define("Cracked Stone Bricks", 2.6);
        CHISELED_STONE_BRICKS_COST = BUILDER.comment("Price for Chiseled Stone Bricks.").define("Chiseled Stone Bricks", 2.8);
        BRICKS_COST = BUILDER.comment("Price for Bricks Block.").define("Bricks", 3.0);
        CLAY_BLOCK_COST = BUILDER.comment("Price for Clay Block.").define("Clay Block", 1.5);
        TERRACOTTA_COST = BUILDER.comment("Price for Terracotta.").define("Terracotta", 2.0);
        WHITE_TERRACOTTA_COST = BUILDER.comment("Price for White Terracotta.").define("White Terracotta", 2.1);
        ORANGE_TERRACOTTA_COST = BUILDER.comment("Price for Orange Terracotta.").define("Orange Terracotta", 2.1);
        MAGENTA_TERRACOTTA_COST = BUILDER.comment("Price for Magenta Terracotta.").define("Magenta Terracotta", 2.1);
        LIGHT_BLUE_TERRACOTTA_COST = BUILDER.comment("Price for Light Blue Terracotta.").define("Light Blue Terracotta", 2.1);
        YELLOW_TERRACOTTA_COST = BUILDER.comment("Price for Yellow Terracotta.").define("Yellow Terracotta", 2.1);
        LIME_TERRACOTTA_COST = BUILDER.comment("Price for Lime Terracotta.").define("Lime Terracotta", 2.1);
        PINK_TERRACOTTA_COST = BUILDER.comment("Price for Pink Terracotta.").define("Pink Terracotta", 2.1);
        GRAY_TERRACOTTA_COST = BUILDER.comment("Price for Gray Terracotta.").define("Gray Terracotta", 2.1);
        LIGHT_GRAY_TERRACOTTA_COST = BUILDER.comment("Price for Light Gray Terracotta.").define("Light Gray Terracotta", 2.1);
        CYAN_TERRACOTTA_COST = BUILDER.comment("Price for Cyan Terracotta.").define("Cyan Terracotta", 2.1);
        PURPLE_TERRACOTTA_COST = BUILDER.comment("Price for Purple Terracotta.").define("Purple Terracotta", 2.1);
        BLUE_TERRACOTTA_COST = BUILDER.comment("Price for Blue Terracotta.").define("Blue Terracotta", 2.1);
        BROWN_TERRACOTTA_COST = BUILDER.comment("Price for Brown Terracotta.").define("Brown Terracotta", 2.1);
        GREEN_TERRACOTTA_COST = BUILDER.comment("Price for Green Terracotta.").define("Green Terracotta", 2.1);
        RED_TERRACOTTA_COST = BUILDER.comment("Price for Red Terracotta.").define("Red Terracotta", 2.1);
        BLACK_TERRACOTTA_COST = BUILDER.comment("Price for Black Terracotta.").define("Black Terracotta", 2.1);
        SANDSTONE_COST = BUILDER.comment("Price for Sandstone.").define("Sandstone", 1.5);
        SMOOTH_SANDSTONE_COST = BUILDER.comment("Price for Smooth Sandstone.").define("Smooth Sandstone", 1.8);
        CUT_SANDSTONE_COST = BUILDER.comment("Price for Cut Sandstone.").define("Cut Sandstone", 1.7);
        CHISELED_SANDSTONE_COST = BUILDER.comment("Price for Chiseled Sandstone.").define("Chiseled Sandstone", 1.9);
        OAK_LOG_COST = BUILDER.comment("Price for Oak Log.").define("Oak Log", 1.0);
        OAK_PLANK_COST = BUILDER.comment("Price for Oak Plank.").define("Oak Plank", 0.5);
        WHITE_WOOL_COST = BUILDER.comment("Price for White Wool.").define("White Wool", 1.2);
        CONCRETE_COST = BUILDER.comment("Price for Concrete Block.").define("Concrete", 1.5);
        GLASS_COST = BUILDER.comment("Price for Glass.").define("Glass", 0.8);
        STAINED_GLASS_COST = BUILDER.comment("Price for Stained Glass.").define("Stained Glass", 1.0);
        ANDESITE_COST = BUILDER.comment("Price for Andesite.").define("Andesite", 1.0);
        POLISHED_ANDESITE_COST = BUILDER.comment("Price for Polished Andesite.").define("Polished Andesite", 1.2);
        BASALT_COST = BUILDER.comment("Price for Basalt.").define("Basalt", 1.5);
        POLISHED_BASALT_COST = BUILDER.comment("Price for Polished Basalt.").define("Polished Basalt", 1.7);
        PURPUR_BLOCK_COST = BUILDER.comment("Price for Purpur Block.").define("Purpur Block", 2.5);
        BOOKSHELF_COST = BUILDER.comment("Price for Bookshelf.").define("Bookshelf", 6.0);
        HAY_BLOCK_COST = BUILDER.comment("Price for Hay Block.").define("Hay Block", 4.0);
        SLIME_BLOCK_COST = BUILDER.comment("Price for Slime Block.").define("Slime Block", 5.0);

        BUILDER.pop();
        SPEC = BUILDER.build();
    }
}
